name: "Release CLI"
description: "Create GitHub release for CLI binaries"

inputs:
  version:
    description: "Version number for the release"
    required: true

runs:
  using: composite
  steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: dist

    - name: Read changelog
      id: changelog
      shell: bash
      run: |
        # Read the changelog file
        CHANGELOG=$(cat apps/cli/CHANGELOG.md)
        VERSION="${{ inputs.version }}"

        # Find the start of the version section
        START_LINE=$(echo "$CHANGELOG" | grep -n "^## $VERSION" | cut -d: -f1)
        if [ -z "$START_LINE" ]; then
          echo "Could not find version $VERSION in changelog"
          exit 1
        fi

        # Find the next version section or end of file
        NEXT_VERSION_LINE=$(echo "$CHANGELOG" | tail -n +$((START_LINE + 1)) | grep -n "^## " | head -n 1 | cut -d: -f1)

        if [ -z "$NEXT_VERSION_LINE" ]; then
          # If no next version found, take everything until the end
          BODY=$(echo "$CHANGELOG" | tail -n +$((START_LINE + 1)))
        else
          # Take content until the next version
          BODY=$(echo "$CHANGELOG" | tail -n +$((START_LINE + 1)) | head -n $((NEXT_VERSION_LINE - 1)))
        fi

        # Clean up the content
        BODY=$(echo "$BODY" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')

        # Set output
        echo "body<<EOF" >> $GITHUB_OUTPUT
        echo "$BODY" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ inputs.version }}
        name: Release v${{ inputs.version }}
        body: ${{ steps.changelog.outputs.body }}
        draft: false
        prerelease: false
        files: |
          dist/acme-linux-x64/acme-linux-x64
          dist/acme-linux-arm64/acme-linux-arm64
          dist/acme-linux-x64-musl/acme-linux-x64-musl
          dist/acme-linux-arm64-musl/acme-linux-arm64-musl
          dist/acme-darwin-x64/acme-darwin-x64
          dist/acme-darwin-arm64/acme-darwin-arm64
          dist/acme-win32-x64/acme-win32-x64.exe
      env:
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}