// Type-safe Stripe price and product definitions
// This file is generated by the build script - DO NOT EDIT MANUALLY
// Generated file: billing-types.generated.ts

/**
 * All available price lookup keys in the Untrace system
 * These are the lookup keys used in Stripe's pricing system
 * SINGLE SOURCE OF TRUTH: All lookup keys are defined here
 */
export const PRICE_LOOKUP_KEYS = {
  // Addon Prices
  DEDICATED_SUPPORT_MONTHLY: 'untrace_dedicated_support_2025_01_monthly',
  DEDICATED_SUPPORT_YEARLY: 'untrace_dedicated_support_2025_01_yearly',
  // Free Plan Prices
  FREE_MONTHLY: 'untrace_free_2025_01_monthly',

  // Team Plan Prices
  TEAM_MONTHLY: 'untrace_team_2025_01_monthly',
  TEAM_YEARLY: 'untrace_team_2025_01_yearly',
} as const;

/**
 * Type representing all available price lookup keys
 */
export type PriceLookupKey =
  (typeof PRICE_LOOKUP_KEYS)[keyof typeof PRICE_LOOKUP_KEYS];

/**
 * All available product IDs in the Untrace system
 * These are the product IDs used in Stripe's product system
 * GENERATED: This will be populated by the build script
 */
export const PRODUCT_IDS = {
  // Addon Products
  DEDICATED_SUPPORT: 'GENERATED_PRODUCT_ID',
  // Plan Products
  FREE_PLAN: 'GENERATED_PRODUCT_ID',
  TEAM_PLAN: 'GENERATED_PRODUCT_ID',
} as const;

/**
 * Type representing all available product IDs
 */
export type ProductId = (typeof PRODUCT_IDS)[keyof typeof PRODUCT_IDS];

/**
 * All available price IDs in the Untrace system
 * These are the actual price IDs from Stripe
 * GENERATED: This will be populated by the build script using PRICE_LOOKUP_KEYS
 */
export const PRICE_IDS: Record<keyof typeof PRICE_LOOKUP_KEYS, string> = {
  // Addon Prices
  DEDICATED_SUPPORT_MONTHLY: 'GENERATED_PRICE_ID',
  DEDICATED_SUPPORT_YEARLY: 'GENERATED_PRICE_ID',
  // Free Plan Prices
  FREE_MONTHLY: 'GENERATED_PRICE_ID',

  // Team Plan Prices
  TEAM_MONTHLY: 'GENERATED_PRICE_ID',
  TEAM_YEARLY: 'GENERATED_PRICE_ID',
} as const;

/**
 * Type representing all available price IDs
 */
export type PriceId = (typeof PRICE_IDS)[keyof typeof PRICE_IDS];

/**
 * Plan types available in the system
 */
export const PLAN_TYPES = {
  FREE: 'free',
  TEAM: 'team',
} as const;

/**
 * Type representing all available plan types
 */
export type PlanType = (typeof PLAN_TYPES)[keyof typeof PLAN_TYPES];

/**
 * Billing intervals available in the system
 */
export const BILLING_INTERVALS = {
  MONTHLY: 'month',
  YEARLY: 'year',
} as const;

/**
 * Type representing all available billing intervals
 */
export type BillingInterval =
  (typeof BILLING_INTERVALS)[keyof typeof BILLING_INTERVALS];
