export interface Competitor {
  category: string;
  comparison: string;
  description: string;
  logo: string;
  marketShare: string;
  name: string;
  pricing: string;
  strengths: string[];
  untraceAdvantages: string[];
  weaknesses: string[];
  website: string;
}

export interface ComparisonRow {
  beeceptor: boolean;
  cloudflare: boolean;
  feature: string;
  hookdeck: boolean;
  localtunnel: boolean;
  mcpServer: boolean;
  ngrok: boolean;
  smee: boolean;
  svix: boolean;
  untrace: boolean;
  webhookSite: boolean;
}

export const competitors: Competitor[] = [
  {
    category: 'Tunneling Platform',
    comparison: '/vs-ngrok',
    description: 'Popular tunneling tool for individual developers',
    logo: '🚇',
    marketShare: 'High',
    name: 'ngrok',
    pricing: 'From $25/month',
    strengths: [
      'Easy to use',
      'Popular',
      'Good documentation',
      'Custom domains',
      'Request inspection',
    ],
    untraceAdvantages: [
      'One shared URL for entire team',
      'Config file in your repo',
      'VS Code integration',
      'No per-domain fees',
      'AI-powered debugging',
      'Team collaboration features',
      'Webhook-specific design',
    ],
    weaknesses: [
      'Expensive for teams',
      'No team features',
      'Per-domain pricing',
      'Not webhook-focused',
      'No editor integration',
    ],
    website: 'https://ngrok.com',
  },
  {
    category: 'Webhook Testing',
    comparison: '/vs-webhook-site',
    description: 'Simple webhook testing and inspection tool',
    logo: '🌐',
    marketShare: 'Medium',
    name: 'Webhook.site',
    pricing: 'From $18/month',
    strengths: [
      'Simple interface',
      'Quick setup',
      'Good for testing',
      'Request inspection',
      'Event replay',
    ],
    untraceAdvantages: [
      'One shared URL for entire team',
      'Config file in your repo',
      'VS Code integration',
      'Professional features',
      'Local development routing',
      'Team collaboration',
      'Custom transformations',
    ],
    weaknesses: [
      'Limited team features',
      'Basic functionality',
      'No editor integration',
      'No local routing',
      'No custom domains',
    ],
    website: 'https://webhook.site',
  },
  {
    category: 'API Mocking',
    comparison: '/vs-beeceptor',
    description: 'API mocking and webhook testing platform',
    logo: '🐝',
    marketShare: 'Medium',
    name: 'Beeceptor',
    pricing: 'From $25/month',
    strengths: [
      'API mocking',
      'Multiple protocols',
      'Good features',
      'Custom responses',
      'Request inspection',
    ],
    untraceAdvantages: [
      'One shared URL for entire team',
      'Config file in your repo',
      'Webhook-focused design',
      'Better pricing',
      'VS Code integration',
      'Local development routing',
      'Team collaboration',
    ],
    weaknesses: [
      'Expensive',
      'General-purpose tool',
      'No webhook focus',
      'No editor integration',
    ],
    website: '',
  },
  {
    category: 'Basic Tunneling',
    comparison: '/vs-localtunnel',
    description: 'Basic tunneling solution (no longer maintained)',
    logo: '🔗',
    marketShare: 'Low',
    name: 'Localtunnel',
    pricing: 'Free',
    strengths: ['Free', 'Simple', 'Open source'],
    untraceAdvantages: [
      'One shared URL for entire team',
      'Config file in your repo',
      'Active maintenance',
      'Enterprise reliability',
      'Team features',
      'VS Code integration',
      'Professional support',
    ],
    weaknesses: [
      'Unmaintained',
      'Unreliable',
      'No team features',
      'Basic functionality',
      'No request inspection',
      'No custom domains',
    ],
    website: 'https://localtunnel.me',
  },
  {
    category: 'Webhook Proxy',
    comparison: '/vs-smee',
    description: 'GitHub webhook proxy for quick testing',
    logo: '🔌',
    marketShare: 'Medium',
    name: 'Smee.io',
    pricing: 'Free',
    strengths: [
      'Free',
      'GitHub integration',
      'Quick setup',
      'Real-time forwarding',
    ],
    untraceAdvantages: [
      'Professional features',
      'Team collaboration',
      'VS Code integration',
      'Persistent URLs',
      'Custom domains',
      'Advanced monitoring',
      'Multiple provider support',
    ],
    weaknesses: [
      'Basic features only',
      'No team support',
      'No authentication',
      'Temporary URLs only',
      'GitHub-focused only',
      'No request inspection',
    ],
    website: 'https://smee.io',
  },
  {
    category: 'Infrastructure Tunneling',
    comparison: '/vs-cloudflare-tunnel',
    description: 'Enterprise-grade secure tunneling solution',
    logo: '☁️',
    marketShare: 'High',
    name: 'Cloudflare Tunnel',
    pricing: 'From $25/month',
    strengths: [
      'Enterprise security',
      'Global network',
      'Zero-trust',
      'Custom domains',
      'High performance',
    ],
    untraceAdvantages: [
      'Built for webhooks',
      'Simple setup',
      'Team collaboration',
      'No DNS requirements',
      'VS Code integration',
      'Request inspection',
      'Better pricing for teams',
    ],
    weaknesses: [
      'Complex setup',
      'Not webhook-focused',
      'Requires Cloudflare DNS',
      'Steep learning curve',
      'No editor integration',
      'No request replay',
    ],
    website: 'https://cloudflare.com',
  },
  {
    category: 'Event Gateway',
    comparison: '/vs-hookdeck',
    description: 'Event gateway for production webhook infrastructure',
    logo: '🎣',
    marketShare: 'Medium',
    name: 'Hookdeck',
    pricing: 'From $39/month',
    strengths: [
      'Production-ready',
      'Advanced routing',
      'Event queuing',
      'Custom transformations',
      'Retry logic',
    ],
    untraceAdvantages: [
      'Development-focused',
      'Simple setup',
      'VS Code integration',
      'Better for testing',
      'Team collaboration',
      'Local development routing',
      'Better pricing',
    ],
    weaknesses: [
      'Complex for development',
      'Higher pricing',
      'No VS Code integration',
      'Production-focused',
      'No local routing',
    ],
    website: 'https://hookdeck.com',
  },
  {
    category: 'Webhook Infrastructure',
    comparison: '/vs-svix',
    description: 'Enterprise webhook infrastructure as a service',
    logo: '🚀',
    marketShare: 'High',
    name: 'Svix',
    pricing: 'From $490/month',
    strengths: [
      'Enterprise-grade',
      'Sending & receiving',
      'Full infrastructure',
      'Advanced security',
      'Custom transformations',
      'Retry logic',
    ],
    untraceAdvantages: [
      'Built for development',
      'Simple team setup',
      'VS Code integration',
      'Testing-focused',
      'Local development routing',
      'Better pricing',
      'Request inspection',
    ],
    weaknesses: [
      'Production-focused',
      'Complex integration',
      'High pricing',
      'Not for testing',
      'No editor integration',
      'No local routing',
    ],
    website: 'https://svix.com',
  },
];

export const comparisonMatrix: ComparisonRow[] = [
  {
    beeceptor: false,
    cloudflare: false,
    feature: 'Shared Webhook URLs',
    hookdeck: false,
    localtunnel: false,
    mcpServer: false,
    ngrok: false,
    smee: false,
    svix: false,
    untrace: true,
    webhookSite: false,
  },
  {
    beeceptor: false,
    cloudflare: false,
    feature: 'Config File in Repo',
    hookdeck: false,
    localtunnel: false,
    mcpServer: false,
    ngrok: false,
    smee: false,
    svix: false,
    untrace: true,
    webhookSite: false,
  },
  {
    beeceptor: false,
    cloudflare: false,
    feature: 'VS Code Integration',
    hookdeck: false,
    localtunnel: false,
    mcpServer: false,
    ngrok: false,
    smee: false,
    svix: false,
    untrace: true,
    webhookSite: false,
  },
  {
    beeceptor: false,
    cloudflare: true,
    feature: 'Custom Domains Included',
    hookdeck: true,
    localtunnel: false,
    mcpServer: false,
    ngrok: true,
    smee: false,
    svix: true,
    untrace: true,
    webhookSite: false,
  },
  {
    beeceptor: true,
    cloudflare: false,
    feature: 'Event Replay',
    hookdeck: true,
    localtunnel: false,
    mcpServer: true,
    ngrok: true,
    smee: false,
    svix: true,
    untrace: true,
    webhookSite: true,
  },
  {
    beeceptor: false,
    cloudflare: false,
    feature: 'MCP Server',
    hookdeck: false,
    localtunnel: false,
    mcpServer: true,
    ngrok: false,
    smee: false,
    svix: false,
    untrace: true,
    webhookSite: false,
  },
  {
    beeceptor: true,
    cloudflare: true,
    feature: 'Free Tier',
    hookdeck: true,
    localtunnel: true,
    mcpServer: true,
    ngrok: true,
    smee: true,
    svix: true,
    untrace: true,
    webhookSite: true,
  },
  {
    beeceptor: true,
    cloudflare: true,
    feature: 'Enterprise Features',
    hookdeck: true,
    localtunnel: false,
    mcpServer: true,
    ngrok: true,
    smee: false,
    svix: true,
    untrace: true,
    webhookSite: false,
  },
  {
    beeceptor: false,
    cloudflare: false,
    feature: 'Team Collaboration',
    hookdeck: false,
    localtunnel: false,
    mcpServer: false,
    ngrok: false,
    smee: false,
    svix: false,
    untrace: true,
    webhookSite: false,
  },
  {
    beeceptor: false,
    cloudflare: false,
    feature: 'Local Development Routing',
    hookdeck: false,
    localtunnel: false,
    mcpServer: false,
    ngrok: false,
    smee: false,
    svix: false,
    untrace: true,
    webhookSite: false,
  },
  {
    beeceptor: true,
    cloudflare: false,
    feature: 'Request Inspection',
    hookdeck: true,
    localtunnel: false,
    mcpServer: true,
    ngrok: true,
    smee: false,
    svix: true,
    untrace: true,
    webhookSite: true,
  },
  {
    beeceptor: true,
    cloudflare: false,
    feature: 'Custom Transformations',
    hookdeck: true,
    localtunnel: false,
    mcpServer: false,
    ngrok: false,
    smee: false,
    svix: true,
    untrace: true,
    webhookSite: false,
  },
  {
    beeceptor: false,
    cloudflare: false,
    feature: 'AI-Powered Debugging',
    hookdeck: false,
    localtunnel: false,
    mcpServer: false,
    ngrok: false,
    smee: false,
    svix: false,
    untrace: true,
    webhookSite: false,
  },
  {
    beeceptor: false,
    cloudflare: false,
    feature: 'Unlimited Team Members',
    hookdeck: false,
    localtunnel: false,
    mcpServer: false,
    ngrok: false,
    smee: false,
    svix: false,
    untrace: true,
    webhookSite: false,
  },
  {
    beeceptor: false,
    cloudflare: false,
    feature: 'Private Webhook URLs',
    hookdeck: true,
    localtunnel: false,
    mcpServer: false,
    ngrok: true,
    smee: false,
    svix: true,
    untrace: true,
    webhookSite: false,
  },
  {
    beeceptor: false,
    cloudflare: false,
    feature: 'Advanced Analytics',
    hookdeck: true,
    localtunnel: false,
    mcpServer: false,
    ngrok: false,
    smee: false,
    svix: true,
    untrace: true,
    webhookSite: false,
  },
  {
    beeceptor: false,
    cloudflare: false,
    feature: 'External Integrations',
    hookdeck: true,
    localtunnel: false,
    mcpServer: false,
    ngrok: false,
    smee: false,
    svix: true,
    untrace: true,
    webhookSite: false,
  },
  {
    beeceptor: false,
    cloudflare: true,
    feature: 'SSO & SAML',
    hookdeck: true,
    localtunnel: false,
    mcpServer: false,
    ngrok: true,
    smee: false,
    svix: true,
    untrace: true,
    webhookSite: false,
  },
  {
    beeceptor: false,
    cloudflare: true,
    feature: 'Audit Logs',
    hookdeck: true,
    localtunnel: false,
    mcpServer: false,
    ngrok: true,
    smee: false,
    svix: true,
    untrace: true,
    webhookSite: false,
  },
  {
    beeceptor: false,
    cloudflare: true,
    feature: '99.9% Uptime SLA',
    hookdeck: true,
    localtunnel: false,
    mcpServer: false,
    ngrok: true,
    smee: false,
    svix: true,
    untrace: true,
    webhookSite: false,
  },
];
