name: Cove
options:
  bundleIdPrefix: com.cove
  deploymentTarget:
    iOS: 17.0
  generateEmptyDirectories: true
  groupSortPosition: top
packages:
  SwiftLint:
    url: https://github.com/realm/SwiftLint
    version: 0.54.0

targets:
  Models:
    type: framework
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: Sources/Models
    dependencies:
      - sdk: SwiftUI.framework
      - sdk: SwiftData.framework
      - sdk: Foundation.framework
    settings:
      base:
        DEVELOPMENT_TEAM: QG5N3R59QB
        PRODUCT_BUNDLE_IDENTIFIER: com.cove.ios.models
        GENERATE_INFOPLIST_FILE: YES
        # DEFINES_MODULE: YES
        SWIFT_INSTALL_OBJC_HEADER: NO
        SWIFT_EMIT_MODULE_INTERFACE: YES

  # LiveActivity:
  #   type: framework
  #   platform: iOS
  #   deploymentTarget: "17.0"
  #   sources:
  #     - path: Sources/LiveActivity
  #   dependencies:
  #     - target: Models
  #     - sdk: SwiftUI.framework
  #     - sdk: SwiftData.framework
  #     - sdk: Foundation.framework
  #     - sdk: ActivityKit.framework
  #     - sdk: WidgetKit.framework
  #   settings:
  #     base:
  #       DEVELOPMENT_TEAM: QG5N3R59QB
  #       PRODUCT_BUNDLE_IDENTIFIER: com.cove.ios.liveactivity
  #       GENERATE_INFOPLIST_FILE: YES
  #       DEFINES_MODULE: YES
  #       SWIFT_INSTALL_OBJC_HEADER: NO
  #       SWIFT_EMIT_MODULE_INTERFACE: YES
  #       SWIFT_COMPILATION_MODE: wholemodule
  #       OTHER_SWIFT_FLAGS: -enable-library-evolution

  Components:
    type: framework
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: Sources/Components
    dependencies:
      - target: Models
      - sdk: SwiftUI.framework
      - sdk: Charts.framework
      - sdk: Foundation.framework
    settings:
      base:
        DEVELOPMENT_TEAM: QG5N3R59QB
        PRODUCT_BUNDLE_IDENTIFIER: com.cove.ios.components
        GENERATE_INFOPLIST_FILE: YES
        # DEFINES_MODULE: YES
        SWIFT_INSTALL_OBJC_HEADER: NO
        SWIFT_EMIT_MODULE_INTERFACE: YES
        SWIFT_COMPILATION_MODE: wholemodule
        OTHER_SWIFT_FLAGS: -enable-library-evolution

  Services:
    type: framework
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: Sources/Services
    dependencies:
      - target: Models
      # - target: LiveActivity
      - sdk: SwiftData.framework
      - sdk: BackgroundTasks.framework
      - sdk: ActivityKit.framework
      - sdk: UserNotifications.framework
      - sdk: Network.framework
      - sdk: Foundation.framework
    settings:
      base:
        DEVELOPMENT_TEAM: QG5N3R59QB
        PRODUCT_BUNDLE_IDENTIFIER: com.cove.ios.services
        GENERATE_INFOPLIST_FILE: YES
        # DEFINES_MODULE: YES
        SWIFT_INSTALL_OBJC_HEADER: NO
        SWIFT_EMIT_MODULE_INTERFACE: YES

  Cove:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: Sources
        excludes:
          - "Components/**"
          - "Models/**"
          - "Services/**"
          - "Widgets/**"
    dependencies:
      - target: Models
      - target: Components
      - target: Services
      - target: CoveWidgets
      - sdk: WidgetKit.framework
      - sdk: SwiftUI.framework
      - sdk: Intents.framework
    settings:
      base:
        DEVELOPMENT_TEAM: QG5N3R59QB
        INFOPLIST_FILE: Sources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.cove.ios
        CODE_SIGN_ENTITLEMENTS: Sources/Cove.entitlements
    info:
      path: Sources/Info.plist
      properties:
        CFBundleName: Cove
        CFBundleDisplayName: Cove
        UILaunchStoryboardName: LaunchScreen
        NSLocalNetworkUsageDescription: Cove needs to access your local network to discover and control your devices
        NSUserNotificationUsageDescription: Cove needs notifications to alert you about important device events and status changes
        NSAppTransportSecurity:
          NSAllowsLocalNetworking: true
          NSExceptionDomains:
            localhost:
              NSExceptionAllowsInsecureHTTPLoads: true
              NSIncludesSubdomains: true
        NSBonjourServices:
          - _http._tcp
          - _bonjour._tcp
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
        NSHomeKitUsageDescription: "Cove needs access to HomeKit to set up and control your smart locks."
        LSApplicationQueriesSchemes:
          - homekit
    entitlements:
      path: Sources/Cove.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.cove.ios
        com.apple.developer.usernotifications.time-sensitive: true
        com.apple.developer.homekit: true

  CoveWidgets:
    type: app-extension
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: Widgets
      - path: Sources/Intents
    dependencies:
      - target: Models
      - target: Services
      - sdk: WidgetKit.framework
      - sdk: SwiftUI.framework
      - sdk: Intents.framework
    settings:
      base:
        DEVELOPMENT_TEAM: QG5N3R59QB
        PRODUCT_BUNDLE_IDENTIFIER: com.cove.ios.widgets
        INFOPLIST_FILE: Widgets/Info.plist
        CODE_SIGN_ENTITLEMENTS: Widgets/CoveWidgets.entitlements
        ENABLE_BITCODE: NO
        SKIP_INSTALL: YES
        CURRENT_PROJECT_VERSION: 1
        GENERATE_INFOPLIST_FILE: YES
        MARKETING_VERSION: 1.0
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ASSETCATALOG_COMPILER_WIDGET_BACKGROUND_COLOR_NAME: WidgetBackground
    entitlements:
      path: Widgets/CoveWidgets.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.cove.ios
    scheme:
      environmentVariables:
        _XCWidgetKind: DeviceStatusWidget

schemes:
  Cove:
    build:
      targets:
        Models: all
        Components: all
        Services: all
        Cove: all
        CoveWidgets: all
      parallelizeBuild: true
      buildImplicitDependencies: true
    run:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release