export interface IntegrationPlatform {
  category: string;
  integration: string;
  description: string;
  logo: string;
  marketShare: string;
  name: string;
  pricing: string;
  strengths: string[];
  untraceAdvantages: string[];
  weaknesses: string[];
  website: string;
}

export interface IntegrationMatrixRow {
  langtrace: boolean;
  traceloop: boolean;
  laminar: boolean;
  promptfoo: boolean;
  langfuse: boolean;
  helicone: boolean;
  langsmith: boolean;
  arize: boolean;
  datadog: boolean;
  untrace: boolean;
  feature: string;
}

export const integrationPlatforms: IntegrationPlatform[] = [
  {
    category: 'Open Source Observability',
    description:
      'Open-source observability tool for LLM applications with OpenTelemetry support',
    integration: '/integrations/langtrace',
    logo: '🔍',
    marketShare: 'Medium',
    name: 'Langtrace AI',
    pricing: 'Open Source',
    strengths: [
      'Open source',
      'OpenTelemetry support',
      'Multiple observability tools',
      'Good documentation',
      'Community driven',
    ],
    untraceAdvantages: [
      'Seamless trace forwarding',
      'Real-time integration',
      'Custom transformations',
      'Team collaboration',
      'VS Code integration',
      'Advanced filtering',
      'Webhook-specific design',
    ],
    weaknesses: [
      'Limited enterprise features',
      'Self-hosted complexity',
      'No managed service',
      'Basic UI',
      'Limited support',
    ],
    website: 'https://langtrace.ai',
  },
  {
    category: 'LLM Reliability Platform',
    description:
      'LLM reliability platform with continuous feedback loops and evaluations',
    integration: '/integrations/traceloop',
    logo: '🔄',
    marketShare: 'High',
    name: 'Traceloop',
    pricing: 'From $99/month',
    strengths: [
      'Comprehensive evaluations',
      'Multiple provider support',
      'Vector database integration',
      'Advanced monitoring',
      'Production ready',
    ],
    untraceAdvantages: [
      'Direct trace forwarding',
      'Real-time monitoring',
      'Custom routing rules',
      'Team collaboration',
      'VS Code integration',
      'Better pricing',
      'Simplified setup',
    ],
    weaknesses: [
      'Higher pricing',
      'Complex setup',
      'Not development-focused',
      'No local routing',
      'Limited free tier',
    ],
    website: 'https://traceloop.com',
  },
  {
    category: 'Real-time Tracing',
    description:
      'Open-source platform for real-time LLM tracing and evaluation',
    integration: '/integrations/laminar',
    logo: '🌊',
    marketShare: 'Medium',
    name: 'Laminar',
    pricing: 'Open Source',
    strengths: [
      'Real-time traces',
      'Automatic tracing',
      'Popular framework support',
      'Open source',
      'Good performance',
    ],
    untraceAdvantages: [
      'Instant trace forwarding',
      'Custom transformations',
      'Team collaboration',
      'VS Code integration',
      'Local development routing',
      'Better UI/UX',
      'Managed service option',
    ],
    weaknesses: [
      'Self-hosted only',
      'Limited enterprise features',
      'No managed service',
      'Basic integrations',
      'Community support only',
    ],
    website: 'https://lmnr.ai',
  },
  {
    category: 'Evaluation & Tracing',
    description: 'LLM evaluation platform with OpenTelemetry tracing support',
    integration: '/integrations/promptfoo',
    logo: '📊',
    marketShare: 'Medium',
    name: 'Promptfoo',
    pricing: 'From $49/month',
    strengths: [
      'Advanced evaluations',
      'OTLP tracing support',
      'Performance metrics',
      'Debugging tools',
      'Good documentation',
    ],
    untraceAdvantages: [
      'Seamless OTLP forwarding',
      'Real-time integration',
      'Custom transformations',
      'Team collaboration',
      'VS Code integration',
      'Better pricing',
      'Simplified setup',
    ],
    weaknesses: [
      'Evaluation-focused',
      'Limited observability',
      'No real-time monitoring',
      'Complex for simple use cases',
      'Higher learning curve',
    ],
    website: 'https://promptfoo.dev',
  },
  {
    category: 'LLM Observability',
    description:
      'Open-source observability platform built specifically for LLM applications',
    integration: '/integrations/langfuse',
    logo: '📈',
    marketShare: 'High',
    name: 'Langfuse',
    pricing: 'Open Source',
    strengths: [
      'LLM-specific design',
      'Full prompt-response tracing',
      'Open source',
      'Good community',
      'Comprehensive features',
    ],
    untraceAdvantages: [
      'Direct trace forwarding',
      'Real-time integration',
      'Custom transformations',
      'Team collaboration',
      'VS Code integration',
      'Better UI/UX',
      'Managed service option',
    ],
    weaknesses: [
      'Self-hosted complexity',
      'Limited enterprise features',
      'No managed service',
      'Basic integrations',
      'Community support only',
    ],
    website: 'https://langfuse.com',
  },
  {
    category: 'API Observability',
    description: 'Lightweight observability layer for OpenAI-compatible APIs',
    integration: '/integrations/helicone',
    logo: '🚁',
    marketShare: 'Medium',
    name: 'Helicone',
    pricing: 'From $25/month',
    strengths: [
      'Lightweight proxy',
      'OpenAI compatibility',
      'Easy setup',
      'Good performance',
      'Detailed logging',
    ],
    untraceAdvantages: [
      'Direct API integration',
      'Real-time forwarding',
      'Custom transformations',
      'Team collaboration',
      'VS Code integration',
      'Better pricing',
      'Simplified setup',
    ],
    weaknesses: [
      'OpenAI-focused only',
      'Limited provider support',
      'Basic features',
      'No advanced routing',
      'Limited customization',
    ],
    website: 'https://helicone.ai',
  },
  {
    category: 'Unified Observability',
    description:
      'Unified platform for LLM observability, debugging, and testing',
    integration: '/integrations/langsmith',
    logo: '🔧',
    marketShare: 'High',
    name: 'LangSmith',
    pricing: 'From $99/month',
    strengths: [
      'Unified platform',
      'Deep agent tracing',
      'Automated evaluations',
      'Collaborative features',
      'Enterprise ready',
    ],
    untraceAdvantages: [
      'Seamless integration',
      'Real-time forwarding',
      'Custom transformations',
      'Team collaboration',
      'VS Code integration',
      'Better pricing',
      'Simplified setup',
    ],
    weaknesses: [
      'Higher pricing',
      'Complex for simple use cases',
      'Not development-focused',
      'Limited free tier',
      'Steep learning curve',
    ],
    website: 'https://smith.langchain.com',
  },
  {
    category: 'ML Observability',
    description:
      'Comprehensive ML observability for traditional ML and LLM applications',
    integration: '/integrations/arize',
    logo: '📊',
    marketShare: 'High',
    name: 'Arize',
    pricing: 'From $199/month',
    strengths: [
      'Comprehensive ML observability',
      'Advanced drift detection',
      'Interactive tracing',
      'Embedding monitoring',
      'Enterprise features',
    ],
    untraceAdvantages: [
      'Direct trace forwarding',
      'Real-time integration',
      'Custom transformations',
      'Team collaboration',
      'VS Code integration',
      'Better pricing',
      'Simplified setup',
    ],
    weaknesses: [
      'Higher pricing',
      'ML-focused design',
      'Complex for LLM-only',
      'No development focus',
      'Limited free tier',
    ],
    website: 'https://arize.com',
  },
  {
    category: 'Infrastructure Monitoring',
    description:
      'Comprehensive infrastructure monitoring with LLM chain observability',
    integration: '/integrations/datadog',
    logo: '🐕',
    marketShare: 'High',
    name: 'Datadog',
    pricing: 'From $15/month',
    strengths: [
      'Comprehensive monitoring',
      'LLM chain observability',
      'Enterprise features',
      'Global infrastructure',
      'Advanced analytics',
    ],
    untraceAdvantages: [
      'Direct trace forwarding',
      'Real-time integration',
      'Custom transformations',
      'Team collaboration',
      'VS Code integration',
      'Better pricing',
      'Simplified setup',
    ],
    weaknesses: [
      'Infrastructure-focused',
      'Complex for LLM-only',
      'Higher learning curve',
      'Not development-focused',
      'Limited LLM features',
    ],
    website: 'https://datadoghq.com',
  },
];

export const integrationMatrix: IntegrationMatrixRow[] = [
  {
    arize: true,
    datadog: true,
    feature: 'LLM Trace Forwarding',
    helicone: true,
    laminar: true,
    langfuse: true,
    langsmith: true,
    langtrace: true,
    promptfoo: true,
    traceloop: true,
    untrace: true,
  },
  {
    arize: true,
    datadog: true,
    feature: 'OpenTelemetry Support',
    helicone: true,
    laminar: true,
    langfuse: true,
    langsmith: true,
    langtrace: true,
    promptfoo: true,
    traceloop: true,
    untrace: true,
  },
  {
    arize: true,
    datadog: true,
    feature: 'Real-time Monitoring',
    helicone: false,
    laminar: false,
    langfuse: false,
    langsmith: true,
    langtrace: false,
    promptfoo: true,
    traceloop: true,
    untrace: true,
  },
  {
    arize: true,
    datadog: true,
    feature: 'Custom Transformations',
    helicone: false,
    laminar: false,
    langfuse: false,
    langsmith: true,
    langtrace: false,
    promptfoo: true,
    traceloop: true,
    untrace: true,
  },
  {
    arize: false,
    datadog: false,
    feature: 'VS Code Integration',
    helicone: false,
    laminar: false,
    langfuse: false,
    langsmith: false,
    langtrace: false,
    promptfoo: false,
    traceloop: false,
    untrace: true,
  },
  {
    arize: false,
    datadog: false,
    feature: 'Team Collaboration',
    helicone: false,
    laminar: false,
    langfuse: false,
    langsmith: false,
    langtrace: false,
    promptfoo: false,
    traceloop: false,
    untrace: true,
  },
  {
    arize: true,
    datadog: true,
    feature: 'Free Tier',
    helicone: true,
    laminar: true,
    langfuse: true,
    langsmith: true,
    langtrace: true,
    promptfoo: true,
    traceloop: true,
    untrace: true,
  },
  {
    arize: true,
    datadog: true,
    feature: 'Enterprise Features',
    helicone: true,
    laminar: false,
    langfuse: false,
    langsmith: true,
    langtrace: false,
    promptfoo: true,
    traceloop: true,
    untrace: true,
  },
  {
    arize: false,
    datadog: false,
    feature: 'Local Development Routing',
    helicone: false,
    laminar: false,
    langfuse: false,
    langsmith: false,
    langtrace: false,
    promptfoo: false,
    traceloop: false,
    untrace: true,
  },
  {
    arize: true,
    datadog: true,
    feature: 'Request Inspection',
    helicone: true,
    laminar: true,
    langfuse: true,
    langsmith: true,
    langtrace: true,
    promptfoo: true,
    traceloop: true,
    untrace: true,
  },
  {
    arize: true,
    datadog: true,
    feature: 'Advanced Analytics',
    helicone: false,
    laminar: false,
    langfuse: false,
    langsmith: true,
    langtrace: false,
    promptfoo: true,
    traceloop: true,
    untrace: true,
  },
  {
    arize: false,
    datadog: false,
    feature: 'AI-Powered Debugging',
    helicone: false,
    laminar: false,
    langfuse: false,
    langsmith: false,
    langtrace: false,
    promptfoo: false,
    traceloop: false,
    untrace: true,
  },
  {
    arize: false,
    datadog: false,
    feature: 'Unlimited Team Members',
    helicone: false,
    laminar: false,
    langfuse: false,
    langsmith: false,
    langtrace: false,
    promptfoo: false,
    traceloop: false,
    untrace: true,
  },
  {
    arize: true,
    datadog: true,
    feature: 'Private Trace URLs',
    helicone: false,
    laminar: false,
    langfuse: false,
    langsmith: true,
    langtrace: false,
    promptfoo: true,
    traceloop: true,
    untrace: true,
  },
  {
    arize: true,
    datadog: true,
    feature: 'External Integrations',
    helicone: false,
    laminar: false,
    langfuse: false,
    langsmith: true,
    langtrace: false,
    promptfoo: true,
    traceloop: true,
    untrace: true,
  },
  {
    arize: true,
    datadog: true,
    feature: 'SSO & SAML',
    helicone: false,
    laminar: false,
    langfuse: false,
    langsmith: true,
    langtrace: false,
    promptfoo: false,
    traceloop: true,
    untrace: true,
  },
  {
    arize: true,
    datadog: true,
    feature: 'Audit Logs',
    helicone: false,
    laminar: false,
    langfuse: false,
    langsmith: true,
    langtrace: false,
    promptfoo: false,
    traceloop: true,
    untrace: true,
  },
  {
    arize: true,
    datadog: true,
    feature: '99.9% Uptime SLA',
    helicone: false,
    laminar: false,
    langfuse: false,
    langsmith: true,
    langtrace: false,
    promptfoo: false,
    traceloop: true,
    untrace: true,
  },
];

// Legacy exports for backward compatibility
export const competitors = integrationPlatforms;
export const comparisonMatrix = integrationMatrix;
