/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

'use server'

import { b } from '../index';
import type { Check, Checked  } from "../types";
import type { Image, Audio } from "@boundaryml/baml";

import type {  ImprovementSuggestions } from "../types"

import type * as types from "../types"

/**
 * Regular BAML server actions that return direct responses.
 */

/**
 * Executes the "SuggestImprovements" BAML action.
 *
 * This server action calls the underlying BAML function "SuggestImprovements"
 * with the specified parameters.
 *
 * @param { string } seo - Input parameter.
 * @param { string } accessibility - Input parameter.
 * @param { string } structure - Input parameter.
 *
 * @returns {Promise<types.ImprovementSuggestions>} A promise that resolves with the result of the action.
 */
export const SuggestImprovements = async (
  seo: string,
  accessibility: string,
  structure: string,
): Promise<types.ImprovementSuggestions> => {
  return b.SuggestImprovements(
    seo,
    accessibility,
    structure,
  );
};